### PR TITLE
feat(*): option to add language for base_prompt

### PR DESCRIPTION
**Pull request by swarnat**
I come from germany and I got better results, when the prompt is written in the language, where I expect the result.

So I added the option within a parameter, to keep multiple translated base_prompts in project.
Is much easier to use, then to set a custom base prompt.

Disclaimer: I'm completely new to Rust and not really understand the system, why strings cannot compared. So please correct, when there is some mistake.

### CODE REVIEW

**Comment by B-urb** [comment]
Thanks for taking the time to contribute, I will look into this as soon as possible. I like the idea to have the prompt based on language. 👍

**Comment by JigSawFr** [comment]
Nice idea!

**Comment by B-urb** [comment]
I will merge this for now and refactor later, when i get to it 👍 Thanks for putting in the work.

**Pull request merged**
